import { ColorScheme, DefaultMantineColor, MantineThemeOverride } from '@mantine/core';
import { IAppFont } from '@ts/global.types';

export const THEME_CATPPUCCIN = (
  colorScheme: ColorScheme,
  primaryColor: DefaultMantineColor,
  appFont: IAppFont
): MantineThemeOverride => ({
  /** Put your mantine theme override here */
  colorScheme,
  primaryColor,
  fontFamily: `${appFont}, sans-serif`,

  colors: {
    blue: [
      colorScheme === 'dark' ? '#89b4fa' : '#ccdbfc',
      colorScheme === 'dark' ? '#89b4fa' : '#c3d5fc',
      colorScheme === 'dark' ? '#89b4fa' : '#b8cefc',
      colorScheme === 'dark' ? '#89b4fa' : '#abc5fb',
      colorScheme === 'dark' ? '#89b4fa' : '#9cbbfa',
      colorScheme === 'dark' ? '#89b4fa' : '#8aaff9',
      colorScheme === 'dark' ? '#89b4fa' : '#75a1f8',
      colorScheme === 'dark' ? '#89b4fa' : '#5d90f7',
      colorScheme === 'dark' ? '#89b4fa' : '#407df6',
      colorScheme === 'dark' ? '#89b4fa' : '#1e66f5',
    ],
    red: [
      colorScheme === 'dark' ? '#f38ba8' : '#fac2ce',
      colorScheme === 'dark' ? '#f38ba8' : '#f9b7c5',
      colorScheme === 'dark' ? '#f38ba8' : '#f8aabb',
      colorScheme === 'dark' ? '#f38ba8' : '#f79baf',
      colorScheme === 'dark' ? '#f38ba8' : '#f689a1',
      colorScheme === 'dark' ? '#f38ba8' : '#f57490',
      colorScheme === 'dark' ? '#f38ba8' : '#f35c7c',
      colorScheme === 'dark' ? '#f38ba8' : '#f13f65',
      colorScheme === 'dark' ? '#f38ba8' : '#ef1d4a',
      colorScheme === 'dark' ? '#f38ba8' : '#d20f39',
    ],
    green: [
      colorScheme === 'dark' ? '#a6e3a1' : '#cff0c7',
      colorScheme === 'dark' ? '#a6e3a1' : '#c6edbd',
      colorScheme === 'dark' ? '#a6e3a1' : '#bceab1',
      colorScheme === 'dark' ? '#a6e3a1' : '#b0e6a3',
      colorScheme === 'dark' ? '#a6e3a1' : '#a2e293',
      colorScheme === 'dark' ? '#a6e3a1' : '#92dd80',
      colorScheme === 'dark' ? '#a6e3a1' : '#7fd76a',
      colorScheme === 'dark' ? '#a6e3a1' : '#68d050',
      colorScheme === 'dark' ? '#a6e3a1' : '#4fc435',
      colorScheme === 'dark' ? '#a6e3a1' : '#40a02b',
    ],
    orange: [
      colorScheme === 'dark' ? '#fab387' : '#fedac6',
      colorScheme === 'dark' ? '#fab387' : '#fed4bc',
      colorScheme === 'dark' ? '#fab387' : '#fecdb0',
      colorScheme === 'dark' ? '#fab387' : '#fec4a2',
      colorScheme === 'dark' ? '#fab387' : '#feba92',
      colorScheme === 'dark' ? '#fab387' : '#feae7f',
      colorScheme === 'dark' ? '#fab387' : '#fea069',
      colorScheme === 'dark' ? '#fab387' : '#fe8f4f',
      colorScheme === 'dark' ? '#fab387' : '#fe7b30',
      colorScheme === 'dark' ? '#fab387' : '#fe640b',
    ],
    yellow: [
      colorScheme === 'dark' ? '#f9e2af' : '#f8e5ca',
      colorScheme === 'dark' ? '#f9e2af' : '#f7e0c1',
      colorScheme === 'dark' ? '#f9e2af' : '#f6dab6',
      colorScheme === 'dark' ? '#f9e2af' : '#f4d4a9',
      colorScheme === 'dark' ? '#f9e2af' : '#f2cc9a',
      colorScheme === 'dark' ? '#f9e2af' : '#f0c388',
      colorScheme === 'dark' ? '#f9e2af' : '#edb973',
      colorScheme === 'dark' ? '#f9e2af' : '#eaad5a',
      colorScheme === 'dark' ? '#f9e2af' : '#e69f3d',
      colorScheme === 'dark' ? '#f9e2af' : '#df8e1d',
    ],
    violet: [
      colorScheme === 'dark' ? '#b4befe' : '#dee3fd',
      colorScheme === 'dark' ? '#b4befe' : '#d8defd',
      colorScheme === 'dark' ? '#b4befe' : '#d1d8fd',
      colorScheme === 'dark' ? '#b4befe' : '#c9d1fd',
      colorScheme === 'dark' ? '#b4befe' : '#c0c9fd',
      colorScheme === 'dark' ? '#b4befe' : '#b5c0fd',
      colorScheme === 'dark' ? '#b4befe' : '#a8b5fd',
      colorScheme === 'dark' ? '#b4befe' : '#99a8fd',
      colorScheme === 'dark' ? '#b4befe' : '#8799fd',
      colorScheme === 'dark' ? '#b4befe' : '#7287fd',
    ],
    pink: [
      colorScheme === 'dark' ? '#f5c2e7' : '#fae0f3',
      colorScheme === 'dark' ? '#f5c2e7' : '#f9daf1',
      colorScheme === 'dark' ? '#f5c2e7' : '#f8d4ef',
      colorScheme === 'dark' ? '#f5c2e7' : '#f7ccec',
      colorScheme === 'dark' ? '#f5c2e7' : '#f6c3e9',
      colorScheme === 'dark' ? '#f5c2e7' : '#f4b8e5',
      colorScheme === 'dark' ? '#f5c2e7' : '#f2abe0',
      colorScheme === 'dark' ? '#f5c2e7' : '#f09cda',
      colorScheme === 'dark' ? '#f5c2e7' : '#ed8bd3',
      colorScheme === 'dark' ? '#f5c2e7' : '#ea76cb',
    ],
    grape: [
      colorScheme === 'dark' ? '#cba6f7' : '#e4d1fb',
      colorScheme === 'dark' ? '#cba6f7' : '#dfc9fa',
      colorScheme === 'dark' ? '#cba6f7' : '#d9bff9',
      colorScheme === 'dark' ? '#cba6f7' : '#d2b4f8',
      colorScheme === 'dark' ? '#cba6f7' : '#caa7f7',
      colorScheme === 'dark' ? '#cba6f7' : '#c197f6',
      colorScheme === 'dark' ? '#cba6f7' : '#b685f5',
      colorScheme === 'dark' ? '#cba6f7' : '#a970f3',
      colorScheme === 'dark' ? '#cba6f7' : '#9a57f1',
      colorScheme === 'dark' ? '#cba6f7' : '#8839ef',
    ],
    teal: [
      colorScheme === 'dark' ? '#8bd5ca' : '#bcf1f5',
      colorScheme === 'dark' ? '#8bd5ca' : '#b0eff3',
      colorScheme === 'dark' ? '#8bd5ca' : '#a2ecf1',
      colorScheme === 'dark' ? '#8bd5ca' : '#92e9ee',
      colorScheme === 'dark' ? '#8bd5ca' : '#7fe5eb',
      colorScheme === 'dark' ? '#8bd5ca' : '#68e1e8',
      colorScheme === 'dark' ? '#8bd5ca' : '#4ddce4',
      colorScheme === 'dark' ? '#8bd5ca' : '#2ed6df',
      colorScheme === 'dark' ? '#8bd5ca' : '#1ebcc5',
      colorScheme === 'dark' ? '#8bd5ca' : '#179299',
    ],
    cyan: [
      colorScheme === 'dark' ? '#89dceb' : '#bfecfc',
      colorScheme === 'dark' ? '#89dceb' : '#b4e9fc',
      colorScheme === 'dark' ? '#89dceb' : '#a7e5fc',
      colorScheme === 'dark' ? '#89dceb' : '#98e0fc',
      colorScheme === 'dark' ? '#89dceb' : '#86dafc',
      colorScheme === 'dark' ? '#89dceb' : '#71d4fc',
      colorScheme === 'dark' ? '#89dceb' : '#58cdfc',
      colorScheme === 'dark' ? '#89dceb' : '#3bc4fc',
      colorScheme === 'dark' ? '#89dceb' : '#18bafb',
      colorScheme === 'dark' ? '#89dceb' : '#04a5e5',
    ],
    lime: [
      colorScheme === 'dark' ? '#74c7ec' : '#c3eef5',
      colorScheme === 'dark' ? '#74c7ec' : '#b9ebf3',
      colorScheme === 'dark' ? '#74c7ec' : '#ade7f1',
      colorScheme === 'dark' ? '#74c7ec' : '#9fe3ee',
      colorScheme === 'dark' ? '#74c7ec' : '#8edeeb',
      colorScheme === 'dark' ? '#74c7ec' : '#7ad8e8',
      colorScheme === 'dark' ? '#74c7ec' : '#63d1e4',
      colorScheme === 'dark' ? '#74c7ec' : '#48c9df',
      colorScheme === 'dark' ? '#74c7ec' : '#28bfd9',
      colorScheme === 'dark' ? '#74c7ec' : '#209fb5',
    ],
    indigo: [
      colorScheme === 'dark' ? '#89b4fa' : '#ccdbfc',
      colorScheme === 'dark' ? '#89b4fa' : '#c3d5fc',
      colorScheme === 'dark' ? '#89b4fa' : '#b8cefc',
      colorScheme === 'dark' ? '#89b4fa' : '#abc5fb',
      colorScheme === 'dark' ? '#89b4fa' : '#9cbbfa',
      colorScheme === 'dark' ? '#89b4fa' : '#8aaff9',
      colorScheme === 'dark' ? '#89b4fa' : '#75a1f8',
      colorScheme === 'dark' ? '#89b4fa' : '#5d90f7',
      colorScheme === 'dark' ? '#89b4fa' : '#407df6',
      colorScheme === 'dark' ? '#89b4fa' : '#1e66f5',
    ],
    dark: [
      colorScheme === 'dark' ? '#a6adc8' : '#dce0e8',
      colorScheme === 'dark' ? '#9399b2' : '#e6e9ef',
      colorScheme === 'dark' ? '#7f849c' : '#eff1f5',
      colorScheme === 'dark' ? '#6c7086' : '#ccd0da',
      colorScheme === 'dark' ? '#585b70' : '#bcc0cc',
      colorScheme === 'dark' ? '#45475a' : '#acb0be',
      colorScheme === 'dark' ? '#313244' : '#9ca0b0',
      colorScheme === 'dark' ? '#1e1e2e' : '#8c8fa1',
      colorScheme === 'dark' ? '#181825' : '#7c7f93',
      colorScheme === 'dark' ? '#11111b' : '#6c6f85',
    ],
    gray: [
      colorScheme === 'dark' ? '#cdd6f4' : '#eff1f5',
      colorScheme === 'dark' ? '#bac2de' : '#ccd0da',
      colorScheme === 'dark' ? '#a6adc8' : '#bcc0cc',
      colorScheme === 'dark' ? '#9399b2' : '#acb0be',
      colorScheme === 'dark' ? '#7f849c' : '#9ca0b0',
      colorScheme === 'dark' ? '#6c7086' : '#8c8fa1',
      colorScheme === 'dark' ? '#585b70' : '#7c7f93',
      colorScheme === 'dark' ? '#45475a' : '#6c6f85',
      colorScheme === 'dark' ? '#313244' : '#5c5f77',
      colorScheme === 'dark' ? '#1e1e2e' : '#4c4f69',
    ],
  },
});
