name: Deploy Edge Functions - dev

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_DEV }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase functions deploy hello --project-ref $PROJECT_ID
